### ISSUE TITLE
AttributeError: module 'openal' has no attribute 'oalGetListener'

### ISSUE THREAD

**Issue by ShaunKulesa** [Zuzu-Typ/PyOpenAL#15]
I'm trying to use the function oalGetListener but it can find it.

```
sound_listner = openal.oalGetListener()
```
This is from a game engine someone made and i'm trying to set it up.

**Comment by Zuzu-Typ** [comment]
This is what I get when testing PyOpenAL 0.7.11a1 in the shell:
```Python
>>> import openal
>>> openal
<module 'openal' from 'C:\\Python39\\lib\\site-packages\\openal\\__init__.py'>
>>> openal.oalGetListener
<function oalGetListener at 0x000001904E7B2A60>
```

It seems that the module "openal" you have isn't PyOpenAL.

Could you please give more information about your setup and the game engine you're trying to use?

Cheers
--Zuzu_Typ--

**Comment by ShaunKulesa** [comment]
```
>>> import openal
>>> openal
<module 'openal' from 'C:\\Users\\Home\\AppData\\Local\\Programs\\Python\\Python39\\Lib\\openal\\__init__.py'>
>>> openal.oalGetListener
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'openal' has no attribute 'oalGetListener'
```

im installing by pip install PyOpenAL

im on windows 10

and its Py3DEngine

**Comment by Zuzu-Typ** [comment]
Oh okay. Hm. That's odd.
The engine you're using shouldn't interfere with PyOpenAL.
`oalGetListener` should always be exported unless an error is thrown.

From what I remember, every public version of PyOpenAL included `oalGetListener`, so that shouldn't be the problem either.
Besides you should have the latest version anyway.

I'm also using Windows 10 and Python 3.9, so that shouldn't be a problem either.

Could you please try listing all attributes of the `openal` module instance?
Maybe that will answer some questions.
This is what I get:
```Python
>>> import openal
>>> dir(openal)
['ALCError', 'ALC_ALL_ATTRIBUTES', 'ALC_ATTRIBUTES_SIZE', 'ALC_CAPTURE_DEFAULT_DEVICE_SPECIFIER', 'ALC_CAPTURE_DEVICE_SPECIFIER', 'ALC_CAPTURE_SAMPLES', 'ALC_DEFAULT_DEVICE_SPECIFIER', 'ALC_DEVICE_SPECIFIER', 'ALC_EXTENSIONS', 'ALC_FALSE', 'ALC_FREQUENCY', 'ALC_INVALID_CONTEXT', 'ALC_INVALID_DEVICE', 'ALC_INVALID_ENUM', 'ALC_INVALID_VALUE', 'ALC_MAJOR_VERSION', 'ALC_MINOR_VERSION', 'ALC_MONO_SOURCES', 'ALC_NO_ERROR', 'ALC_OUT_OF_MEMORY', 'ALC_REFRESH', 'ALC_STEREO_SOURCES', 'ALC_SYNC', 'ALC_TRUE', 'ALError', 'AL_BITS', 'AL_BUFFER', 'AL_BUFFERS_PROCESSED', 'AL_BUFFERS_QUEUED', 'AL_BYTE_OFFSET', 'AL_CHANNELS', 'AL_CONE_INNER_ANGLE', 'AL_CONE_OUTER_ANGLE', 'AL_CONE_OUTER_GAIN', 'AL_DIRECTION', 'AL_DISTANCE_MODEL', 'AL_DOPPLER_FACTOR', 'AL_DOPPLER_VELOCITY', 'AL_EXPONENT_DISTANCE', 'AL_EXPONENT_DISTANCE_CLAMPED', 'AL_EXTENSIONS', 'AL_FALSE', 'AL_FORMAT_MONO16', 'AL_FORMAT_MONO8', 'AL_FORMAT_STEREO16', 'AL_FORMAT_STEREO8', 'AL_FREQUENCY', 'AL_GAIN', 'AL_INITIAL', 'AL_INVALID_ENUM', 'AL_INVALID_NAME', 'AL_INVALID_OPERATION', 'AL_INVALID_VALUE', 'AL_INVERSE_DISTANCE', 'AL_INVERSE_DISTANCE_CLAMPED', 'AL_LINEAR_DISTANCE', 'AL_LINEAR_DISTANCE_CLAMPED', 'AL_LOOPING', 'AL_MAX_DISTANCE', 'AL_MAX_GAIN', 'AL_MIN_GAIN', 'AL_NONE', 'AL_NO_ERROR', 'AL_ORIENTATION', 'AL_OUT_OF_MEMORY', 'AL_PAUSED', 'AL_PENDING', 'AL_PITCH', 'AL_PLAYING', 'AL_POSITION', 'AL_PROCESSED', 'AL_REFERENCE_DISTANCE', 'AL_RENDERER', 'AL_ROLLOFF_FACTOR', 'AL_SAMPLE_OFFSET', 'AL_SEC_OFFSET', 'AL_SIZE', 'AL_SOURCE_RELATIVE', 'AL_SOURCE_STATE', 'AL_SOURCE_TYPE', 'AL_SPEED_OF_SOUND', 'AL_STATIC', 'AL_STOPPED', 'AL_STREAMING', 'AL_TRUE', 'AL_UNDETERMINED', 'AL_UNUSED', 'AL_VELOCITY', 'AL_VENDOR', 'AL_VERSION', 'ALboolean', 'ALbyte', 'ALchar', 'ALdouble', 'ALenum', 'ALfloat', 'ALint', 'ALshort', 'ALsizei', 'ALubyte', 'ALuint', 'ALushort', 'Buffer', 'Listener', 'MAX_FLOAT', 'OAL_DONT_AUTO_INIT', 'OAL_STREAM_BUFFER_COUNT', 'OalError', 'OalWarning', 'PYOGG_AVAIL', 'Source', 'SourceStream', 'StreamBuffer', 'WAVE_AVAIL', 'WAVE_STREAM_BUFFER_SIZE', 'WaveFile', 'WaveFileStream', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '_alError', '_buffers', '_channels_to_al', '_check', '_err', '_format_enum', '_listener', '_no_pyogg_error', '_oalcontext', '_oaldevice', '_sources', '_to_c_int', '_to_c_uint', '_to_int', '_to_val', 'al', 'alBuffer3f', 'alBuffer3i', 'alBufferData', 'alBufferf', 'alBufferfv', 'alBufferi', 'alBufferiv', 'alDeleteBuffers', 'alDeleteSources', 'alDisable', 'alDistanceModel', 'alDopplerFactor', 'alDopplerVelocity', 'alEnable', 'alGenBuffers', 'alGenSources', 'alGetBoolean', 'alGetBooleanv', 'alGetBuffer3f', 'alGetBuffer3i', 'alGetBufferf', 'alGetBufferfv', 'alGetBufferi', 'alGetBufferiv', 'alGetDouble', 'alGetDoublev', 'alGetEnumValue', 'alGetError', 'alGetFloat', 'alGetFloatv', 'alGetInteger', 'alGetIntegerv', 'alGetListener3f', 'alGetListener3i', 'alGetListenerf', 'alGetListenerfv', 'alGetListeneri', 'alGetListeneriv', 'alGetProcAddress', 'alGetSource3f', 'alGetSource3i', 'alGetSourcef', 'alGetSourcefv', 'alGetSourcei', 'alGetSourceiv', 'alGetString', 'alIsBuffer', 'alIsEnabled', 'alIsExtensionPresent', 'alIsSource', 'alListener3f', 'alListener3i', 'alListenerf', 'alListenerfv', 'alListeneri', 'alListeneriv', 'alSource3f', 'alSource3i', 'alSourcePause', 'alSourcePausev', 'alSourcePlay', 'alSourcePlayv', 'alSourceQueueBuffers', 'alSourceRewind', 'alSourceRewindv', 'alSourceStop', 'alSourceStopv', 'alSourceUnqueueBuffers', 'alSourcef', 'alSourcefv', 'alSourcei', 'alSourceiv', 'alSpeedOfSound', 'al_check_error', 'al_enums', 'al_lib', 'alc', 'alcCaptureCloseDevice', 'alcCaptureOpenDevice', 'alcCaptureSamples', 'alcCaptureStart', 'alcCaptureStop', 'alcCloseDevice', 'alcCreateContext', 'alcDestroyContext', 'alcGetContextsDevice', 'alcGetCurrentContext', 'alcGetEnumValue', 'alcGetError', 'alcGetIntegerv', 'alcGetProcAddress', 'alcGetString', 'alcIsExtensionPresent', 'alcMakeContextCurrent', 'alcOpenDevice', 'alcProcessContext', 'alcSuspendContext', 'alc_check_error', 'alc_enums', 'ctypes', 'k', 'lib', 'library_loader', 'local_items', 'long', 'oalGetALCEnum', 'oalGetALEnum', 'oalGetContext', 'oalGetDevice', 'oalGetEnum', 'oalGetInit', 'oalGetListener', 'oalInit', 'oalOpen', 'oalQuit', 'oalSetAutoInit', 'oalSetStreamBufferCount', 'oalStream', 'os', 'sys', 'tuple_add3', 'v', 'warnings', 'wave', 'waveSetStreamBufferSize']
```

**Comment by ShaunKulesa** [comment]
```
>>> import openal
>>> dir(openal)           
['OpenALDriver', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '_debug', '_debug_buffers', 'adaptation', 'create_audio_driver', 'interface', 'lib_alc', 'lib_openal', 'pyglet']
```
The engine isnt interfering, im doing this in cmd

**Comment by Zuzu-Typ** [comment]
Ah I see, as I mentioned before, the module you're using isn't PyOpenAL.
It appears to be `pyglet.media.drivers.openal`.
Not sure how that happened, but if you look at `C:\\Users\\Home\\AppData\\Local\\Programs\\Python\\Python39\\Lib\\openal` and open `__init__.py` with a text editor, you should see that it's part of pyglet and not PyOpenAL.

That's not where pyglet is normally installed though.

**Comment by ShaunKulesa** [comment]
i will just uninstall pyglet

**Comment by ShaunKulesa** [comment]
guess what.

```
>>> import openal
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Home\AppData\Local\Programs\Python\Python39\Lib\openal\__init__.py", line 36, in <module>
    from .adaptation import OpenALDriver
  File "C:\Users\Home\AppData\Local\Programs\Python\Python39\Lib\openal\adaptation.py", line 38, in <module>
    import pyglet
ModuleNotFoundError: No module named 'pyglet'```

**Comment by Zuzu-Typ** [comment]
Just delete the `openal` folder (`C:\Users\Home\AppData\Local\Programs\Python\Python39\Lib\openal`). Then reinstall it and it should be fixed.
Maybe you should try uninstalling PyOpenAL first, so pip doesn't get confused
