### ISSUE TITLE
Noise instead of music

### ISSUE THREAD

**Issue by ivan-enzhaev** [Zuzu-Typ/PyOpenAL#23]
Hello. I try to play a free sound from itch: https://snabisch.itch.io/mario-pants-music-free but I hear a noise. I tried to delete the second channel but it didn't help. You can download this MONO file: [pyopenal-example-wav.zip](https://github.com/user-attachments/files/15804353/pyopenal-example-wav.zip) Be careful it is too loud!

```python
# import PyOpenAL (will require an OpenAL shared library)
from openal import * 

# import the time module, for sleeping during playback
import time

# open our wave file
source = oalOpen("infant_tour.wav")

# and start playback
source.play()

# check if the file is still playing
while source.get_state() == AL_PLAYING:
	# wait until the file is done playing
	time.sleep(1)
	
# release resources (don't forget this)
oalQuit()

```

![image](https://github.com/Zuzu-Typ/PyOpenAL/assets/3908473/225b3705-fa72-4d97-a327-3015ccc6d2a8)

**Comment by ivan-enzhaev** [comment]
What is a correct setting for exporting files from Audacity? I have a MONO file that plays well but when I export it from Audacity with settings as above (MONO8) I have this error:

```
Traceback (most recent call last):
  File "main.py", line 24, in <module>
    w = Widget()
  File "main.py", line 17, in __init__
    self.source = oalOpen("assets/bounce.wav")
  File "E:\ProgramFiles\Python\Python38\lib\site-packages\openal\__init__.py", line 857, in oalOpen
    buffer_ = Buffer(file_)
  File "E:\ProgramFiles\Python\Python38\lib\site-packages\openal\__init__.py", line 350, in __init__
    self.fill(*args)
  File "E:\ProgramFiles\Python\Python38\lib\site-packages\openal\__init__.py", line 370, in fill
    alBufferData(self._getui(), _channels_to_al(file_.channels), file_.buffer, _to_c_int(file_.buffer_length), _to_c_int(file_.frequency))
  File "E:\ProgramFiles\Python\Python38\lib\site-packages\openal\al.py", line 92, in al_check_error
    raise ALError(al_enums[err][0])
openal.al.ALError: AL_INVALID_VALUE
```

**Comment by ivan-enzhaev** [comment]
I see settings for a file that plays well. It is "32-bit float":

![image](https://github.com/Zuzu-Typ/PyOpenAL/assets/3908473/937a8a0c-8e6d-4b80-b5fc-fb26ffd4e40b)

But when I export with this settings:

![image](https://github.com/Zuzu-Typ/PyOpenAL/assets/3908473/ff0827fe-33d7-4e34-9fbb-b138c9015488)

I see this error `unknown format`:

```
Traceback (most recent call last):
  File "main.py", line 24, in <module>
    w = Widget()
  File "main.py", line 17, in __init__
    self.source = oalOpen("assets/bounce.wav")
  File "E:\ProgramFiles\Python\Python38\lib\site-packages\openal\__init__.py", line 853, in oalOpen
    file_ = WaveFile(path)
  File "E:\ProgramFiles\Python\Python38\lib\site-packages\openal\__init__.py", line 137, in __init__
    self.file_ = wave.open(path)
  File "E:\ProgramFiles\Python\Python38\lib\wave.py", line 510, in open
    return Wave_read(f)
  File "E:\ProgramFiles\Python\Python38\lib\wave.py", line 164, in __init__
    self.initfp(f)
  File "E:\ProgramFiles\Python\Python38\lib\wave.py", line 144, in initfp
    self._read_fmt_chunk(chunk)
  File "E:\ProgramFiles\Python\Python38\lib\wave.py", line 269, in _read_fmt_chunk
    raise Error('unknown format: %r' % (wFormatTag,))
wave.Error: unknown format: 3
```

**Comment by ivan-enzhaev** [comment]
I have found a correct format for export! It works
 now!

![image](https://github.com/Zuzu-Typ/PyOpenAL/assets/3908473/c96b7507-1579-4b6a-b10d-698239d639de)
